// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AdventureWorksDemo.Data.Tests.reqnroll.Features.Service
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ProductCategoryServiceTestsFeature
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "ProductCategoryServiceTests.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, System.Threading.Thread.CurrentThread.ManagedThreadId.ToString());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Service", "ProductCategoryServiceTests", "A short summary of the feature", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "ProductCategoryServiceTests")))
            {
                await global::AdventureWorksDemo.Data.Tests.reqnroll.Features.Service.ProductCategoryServiceTestsFeature.FeatureSetupAsync(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 4
#line hidden
#line 5
 await testRunner.GivenAsync("The service to test is \'AdventureWorksDemo.Data.Services.IProductCategoryService\'" +
                    "", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAsync01")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceTests")]
        public async System.Threading.Tasks.Task FindAsync01()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("FindAsync01", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                Reqnroll.Table table1 = new Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table1.AddRow(new string[] {
                            "productCategoryId",
                            "1",
                            "int"});
#line 7
 await testRunner.WhenAsync("I call the method \'FindAsync\' with the parameter values", ((string)(null)), table1, "When ");
#line hidden
                Reqnroll.Table table2 = new Reqnroll.Table(new string[] {
                            "Expected"});
                table2.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Models.ProductCategoryModel"});
#line 10
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table2, "Then ");
#line hidden
                Reqnroll.Table table3 = new Reqnroll.Table(new string[] {
                            "ModifiedDate",
                            "Name",
                            "ParentProductCategoryId",
                            "ProductCategoryId",
                            "Rowguid"});
                table3.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Bikes",
                            "",
                            "1",
                            "cfbda25c-df71-47a7-b81b-64ee161aa37c"});
#line 13
 await testRunner.AndAsync("the result is", ((string)(null)), table3, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAsync04")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceTests")]
        public async System.Threading.Tasks.Task FindAsync04()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("FindAsync04", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                Reqnroll.Table table4 = new Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table4.AddRow(new string[] {
                            "productCategoryId",
                            "4",
                            "int"});
#line 17
 await testRunner.WhenAsync("I call the method \'FindAsync\' with the parameter values", ((string)(null)), table4, "When ");
#line hidden
                Reqnroll.Table table5 = new Reqnroll.Table(new string[] {
                            "Expected"});
                table5.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Models.ProductCategoryModel"});
#line 20
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table5, "Then ");
#line hidden
                Reqnroll.Table table6 = new Reqnroll.Table(new string[] {
                            "ModifiedDate",
                            "Name",
                            "ParentProductCategoryId",
                            "ProductCategoryId",
                            "Rowguid"});
                table6.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Accessories",
                            "",
                            "4",
                            "2be3be36-d9a2-4eee-b593-ed895d97c2a6"});
#line 23
 await testRunner.AndAsync("the result is", ((string)(null)), table6, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAsync1234")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceTests")]
        public async System.Threading.Tasks.Task FindAsync1234()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("FindAsync1234", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                Reqnroll.Table table7 = new Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table7.AddRow(new string[] {
                            "productCategoryId",
                            "1234",
                            "int"});
#line 28
 await testRunner.WhenAsync("I call the method \'FindAsync\' with the parameter values", ((string)(null)), table7, "When ");
#line hidden
                Reqnroll.Table table8 = new Reqnroll.Table(new string[] {
                            "Expected"});
                table8.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Models.ProductCategoryModel"});
#line 32
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table8, "Then ");
#line hidden
#line 35
 await testRunner.AndAsync("the result is null", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAllAsync_1_5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceTests")]
        public async System.Threading.Tasks.Task FindAllAsync_1_5()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("FindAllAsync_1_5", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 37
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                Reqnroll.Table table9 = new Reqnroll.Table(new string[] {
                            "PageNumber",
                            "PageSize"});
                table9.AddRow(new string[] {
                            "1",
                            "5"});
#line 38
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Paging.PagingFilter\'", ((string)(null)), table9, "When ");
#line hidden
                Reqnroll.Table table10 = new Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table10.AddRow(new string[] {
                            "pageingFilter",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Paging.PagingFilter"});
#line 41
 await testRunner.AndAsync("I call the method \'FindAllAsync\' with the parameter values", ((string)(null)), table10, "And ");
#line hidden
                Reqnroll.Table table11 = new Reqnroll.Table(new string[] {
                            "Expected"});
                table11.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Paging.PagedList<AdventureWorksDemo.Data.Models.ProductCa" +
                                "tegoryModel>"});
#line 44
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table11, "Then ");
#line hidden
                Reqnroll.Table table12 = new Reqnroll.Table(new string[] {
                            "ModifiedDate",
                            "Name",
                            "ParentProductCategoryId",
                            "ProductCategoryId",
                            "Rowguid"});
                table12.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Accessories",
                            "",
                            "4",
                            "2be3be36-d9a2-4eee-b593-ed895d97c2a6"});
                table12.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Bikes",
                            "",
                            "1",
                            "cfbda25c-df71-47a7-b81b-64ee161aa37c"});
                table12.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Components",
                            "",
                            "2",
                            "c657828d-d808-4aba-91a3-af2ce02300e9"});
                table12.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Clothing",
                            "",
                            "3",
                            "10a7c342-ca82-48d4-8a38-46a2eb089b74"});
                table12.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Mountain Bikes",
                            "1",
                            "5",
                            "2d364ade-264a-433c-b092-4fcbf3804e01"});
#line 47
 await testRunner.AndAsync("the results are", ((string)(null)), table12, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAllAsync_2_5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceTests")]
        public async System.Threading.Tasks.Task FindAllAsync_2_5()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("FindAllAsync_2_5", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 57
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                Reqnroll.Table table13 = new Reqnroll.Table(new string[] {
                            "PageNumber",
                            "PageSize"});
                table13.AddRow(new string[] {
                            "1",
                            "5"});
#line 58
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Paging.PagingFilter\'", ((string)(null)), table13, "When ");
#line hidden
                Reqnroll.Table table14 = new Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table14.AddRow(new string[] {
                            "pageingFilter",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Paging.PagingFilter"});
#line 61
 await testRunner.AndAsync("I call the method \'FindAllAsync\' with the parameter values", ((string)(null)), table14, "And ");
#line hidden
                Reqnroll.Table table15 = new Reqnroll.Table(new string[] {
                            "Expected"});
                table15.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Paging.PagedList<AdventureWorksDemo.Data.Models.ProductCa" +
                                "tegoryModel>"});
#line 64
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table15, "Then ");
#line hidden
                Reqnroll.Table table16 = new Reqnroll.Table(new string[] {
                            "ModifiedDate",
                            "Name",
                            "ParentProductCategoryId",
                            "ProductCategoryId",
                            "Rowguid"});
                table16.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Accessories",
                            "",
                            "4",
                            "2be3be36-d9a2-4eee-b593-ed895d97c2a6"});
                table16.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Bikes",
                            "",
                            "1",
                            "cfbda25c-df71-47a7-b81b-64ee161aa37c"});
                table16.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Components",
                            "",
                            "2",
                            "c657828d-d808-4aba-91a3-af2ce02300e9"});
                table16.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Clothing",
                            "",
                            "3",
                            "10a7c342-ca82-48d4-8a38-46a2eb089b74"});
                table16.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Mountain Bikes",
                            "1",
                            "5",
                            "2d364ade-264a-433c-b092-4fcbf3804e01"});
#line 67
 await testRunner.AndAsync("the results are", ((string)(null)), table16, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAllAsync_1234_5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceTests")]
        public async System.Threading.Tasks.Task FindAllAsync_1234_5()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("FindAllAsync_1234_5", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 77
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                Reqnroll.Table table17 = new Reqnroll.Table(new string[] {
                            "PageNumber",
                            "PageSize"});
                table17.AddRow(new string[] {
                            "1234",
                            "5"});
#line 78
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Paging.PagingFilter\'", ((string)(null)), table17, "When ");
#line hidden
                Reqnroll.Table table18 = new Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table18.AddRow(new string[] {
                            "pageingFilter",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Paging.PagingFilter"});
#line 81
 await testRunner.AndAsync("I call the method \'FindAllAsync\' with the parameter values", ((string)(null)), table18, "And ");
#line hidden
                Reqnroll.Table table19 = new Reqnroll.Table(new string[] {
                            "Expected"});
                table19.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Paging.PagedList<AdventureWorksDemo.Data.Models.ProductCa" +
                                "tegoryModel>"});
#line 84
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table19, "Then ");
#line hidden
                Reqnroll.Table table20 = new Reqnroll.Table(new string[] {
                            "ModifiedDate",
                            "Name",
                            "ParentProductCategoryId",
                            "ProductCategoryId",
                            "Rowguid"});
#line 87
 await testRunner.AndAsync("the results are", ((string)(null)), table20, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAllAsync_0_5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceTests")]
        public async System.Threading.Tasks.Task FindAllAsync_0_5()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("FindAllAsync_0_5", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 91
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                Reqnroll.Table table21 = new Reqnroll.Table(new string[] {
                            "PageNumber",
                            "PageSize"});
                table21.AddRow(new string[] {
                            "0",
                            "5"});
#line 92
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Paging.PagingFilter\'", ((string)(null)), table21, "When ");
#line hidden
                Reqnroll.Table table22 = new Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table22.AddRow(new string[] {
                            "pageingFilter",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Paging.PagingFilter"});
#line 95
 await testRunner.AndAsync("I call the method \'FindAllAsync\' with the parameter values", ((string)(null)), table22, "And ");
#line hidden
                Reqnroll.Table table23 = new Reqnroll.Table(new string[] {
                            "Expected"});
                table23.AddRow(new string[] {
                            "System.ArgumentOutOfRangeException"});
#line 98
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table23, "Then ");
#line hidden
                Reqnroll.Table table24 = new Reqnroll.Table(new string[] {
                            "Expected"});
                table24.AddRow(new string[] {
                            "Parameter pageNumber must be positive (Parameter \'pageNumber\')"});
#line 101
 await testRunner.AndAsync("the exception message is", ((string)(null)), table24, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAllAsync_0_0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceTests")]
        public async System.Threading.Tasks.Task FindAllAsync_0_0()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("FindAllAsync_0_0", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 105
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                Reqnroll.Table table25 = new Reqnroll.Table(new string[] {
                            "PageNumber",
                            "PageSize"});
                table25.AddRow(new string[] {
                            "0",
                            "0"});
#line 106
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Paging.PagingFilter\'", ((string)(null)), table25, "When ");
#line hidden
                Reqnroll.Table table26 = new Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table26.AddRow(new string[] {
                            "pageingFilter",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Paging.PagingFilter"});
#line 109
 await testRunner.AndAsync("I call the method \'FindAllAsync\' with the parameter values", ((string)(null)), table26, "And ");
#line hidden
                Reqnroll.Table table27 = new Reqnroll.Table(new string[] {
                            "Expected"});
                table27.AddRow(new string[] {
                            "System.ArgumentOutOfRangeException"});
#line 112
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table27, "Then ");
#line hidden
                Reqnroll.Table table28 = new Reqnroll.Table(new string[] {
                            "Expected"});
                table28.AddRow(new string[] {
                            "Parameter pageNumber must be positive (Parameter \'pageNumber\')"});
#line 115
 await testRunner.AndAsync("the exception message is", ((string)(null)), table28, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAllAsync_5_0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceTests")]
        public async System.Threading.Tasks.Task FindAllAsync_5_0()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("FindAllAsync_5_0", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 118
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                Reqnroll.Table table29 = new Reqnroll.Table(new string[] {
                            "PageNumber",
                            "PageSize"});
                table29.AddRow(new string[] {
                            "5",
                            "0"});
#line 119
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Paging.PagingFilter\'", ((string)(null)), table29, "When ");
#line hidden
                Reqnroll.Table table30 = new Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table30.AddRow(new string[] {
                            "pageingFilter",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Paging.PagingFilter"});
#line 122
 await testRunner.AndAsync("I call the method \'FindAllAsync\' with the parameter values", ((string)(null)), table30, "And ");
#line hidden
                Reqnroll.Table table31 = new Reqnroll.Table(new string[] {
                            "Expected"});
                table31.AddRow(new string[] {
                            "System.ArgumentOutOfRangeException"});
#line 125
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table31, "Then ");
#line hidden
                Reqnroll.Table table32 = new Reqnroll.Table(new string[] {
                            "Expected"});
                table32.AddRow(new string[] {
                            "Parameter pageSize must be positive (Parameter \'pageSize\')"});
#line 128
 await testRunner.AndAsync("the exception message is", ((string)(null)), table32, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
