// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AdventureWorksDemo.Data.Tests.reqnroll.Features.Services.ProductCategoryService
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ProductCategoryServiceAddTestsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Services/ProductCategoryService", "ProductCategoryServiceAddTests", "System tests for the ProductCategoryService\r\nTesting the methods AddAsync", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "ProductCategoryServiceAddTests.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
#line hidden
#line 9
 await testRunner.GivenAsync("The service to test is \'AdventureWorksDemo.Data.Services.IProductCategoryService\'" +
                    "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 10
 await testRunner.AndAsync("I don\'t reset the database after the scenario", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AddAsyncNoParent")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceAddTests")]
        public async System.Threading.Tasks.Task AddAsyncNoParent()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("AddAsyncNoParent", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 13
 await testRunner.GivenAsync("I reset the database after the scenario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table156 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "ParentProductCategoryId",
                            "Rowguid"});
                table156.AddRow(new string[] {
                            "PingPong",
                            "",
                            "00000000-1111-0000-0000-000000000002"});
#line 14
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Models.ProductCategoryModel\'", ((string)(null)), table156, "When ");
#line hidden
                global::Reqnroll.Table table157 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table157.AddRow(new string[] {
                            "model",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Models.ProductCategoryModel"});
#line 17
 await testRunner.AndAsync("I call the method \'AddAsync\' with the parameter values", ((string)(null)), table157, "And ");
#line hidden
                global::Reqnroll.Table table158 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table158.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Models.ServiceResult<AdventureWorksDemo.Data.Models.Produ" +
                                "ctCategoryModel>"});
#line 20
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table158, "Then ");
#line hidden
                global::Reqnroll.Table table159 = new global::Reqnroll.Table(new string[] {
                            "IsFailure",
                            "IsSuccess",
                            "Message"});
                table159.AddRow(new string[] {
                            "False",
                            "True",
                            ""});
#line 23
 await testRunner.AndAsync("the result is", ((string)(null)), table159, "And ");
#line hidden
                global::Reqnroll.Table table160 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table160.AddRow(new string[] {
                            "1001",
                            "",
                            "PingPong",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-0000-0000-000000000002"});
#line 26
 await testRunner.AndAsync("the results property \'Value\' contains", ((string)(null)), table160, "And ");
#line hidden
                global::Reqnroll.Table table161 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table161.AddRow(new string[] {
                            "41",
                            "4",
                            "Tires and Tubes",
                            "6/1/2002 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-60e28d47dcdf"});
                table161.AddRow(new string[] {
                            "42",
                            "",
                            "Record to Delete",
                            "6/1/2005 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-000000000001"});
                table161.AddRow(new string[] {
                            "1001",
                            "",
                            "PingPong",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-0000-0000-000000000002"});
#line 29
 await testRunner.AndAsync("the table \'SalesLT.ProductCategory\' filtered by \'ProductCategoryId > 40\' contains" +
                        "", ((string)(null)), table161, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AddAsyncNoParentShortName")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceAddTests")]
        public async System.Threading.Tasks.Task AddAsyncNoParentShortName()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("AddAsyncNoParentShortName", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 36
 await testRunner.GivenAsync("I reset the database after the scenario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table162 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "ParentProductCategoryId",
                            "Rowguid"});
                table162.AddRow(new string[] {
                            "Hi",
                            "",
                            "00000000-1111-0000-0000-000000000002"});
#line 37
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Models.ProductCategoryModel\'", ((string)(null)), table162, "When ");
#line hidden
                global::Reqnroll.Table table163 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table163.AddRow(new string[] {
                            "model",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Models.ProductCategoryModel"});
#line 40
 await testRunner.AndAsync("I call the method \'AddAsync\' with the parameter values", ((string)(null)), table163, "And ");
#line hidden
                global::Reqnroll.Table table164 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table164.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Models.ServiceResult<AdventureWorksDemo.Data.Models.Produ" +
                                "ctCategoryModel>"});
#line 43
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table164, "Then ");
#line hidden
                global::Reqnroll.Table table165 = new global::Reqnroll.Table(new string[] {
                            "IsFailure",
                            "IsSuccess",
                            "Message"});
                table165.AddRow(new string[] {
                            "True",
                            "False",
                            "\'Name\' must be between 3 and 50 characters. You entered 2 characters."});
#line 46
 await testRunner.AndAsync("the result is", ((string)(null)), table165, "And ");
#line hidden
                global::Reqnroll.Table table166 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table166.AddRow(new string[] {
                            "0",
                            "",
                            "Hi",
                            "1/1/0001 12:00:00 AM",
                            "00000000-1111-0000-0000-000000000002"});
#line 50
 await testRunner.AndAsync("the results property \'Value\' contains", ((string)(null)), table166, "And ");
#line hidden
                global::Reqnroll.Table table167 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table167.AddRow(new string[] {
                            "41",
                            "4",
                            "Tires and Tubes",
                            "6/1/2002 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-60e28d47dcdf"});
                table167.AddRow(new string[] {
                            "42",
                            "",
                            "Record to Delete",
                            "6/1/2005 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-000000000001"});
#line 54
 await testRunner.AndAsync("the table \'SalesLT.ProductCategory\' filtered by \'ProductCategoryId > 40\' contains" +
                        "", ((string)(null)), table167, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AddAsyncParent")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceAddTests")]
        public async System.Threading.Tasks.Task AddAsyncParent()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("AddAsyncParent", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 59
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 60
 await testRunner.GivenAsync("I reset the database after the scenario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table168 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "ParentProductCategoryId",
                            "Rowguid"});
                table168.AddRow(new string[] {
                            "PingPong",
                            "42",
                            "00000000-1111-0000-0000-000000000002"});
#line 61
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Models.ProductCategoryModel\'", ((string)(null)), table168, "When ");
#line hidden
                global::Reqnroll.Table table169 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table169.AddRow(new string[] {
                            "model",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Models.ProductCategoryModel"});
#line 64
 await testRunner.AndAsync("I call the method \'AddAsync\' with the parameter values", ((string)(null)), table169, "And ");
#line hidden
                global::Reqnroll.Table table170 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table170.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Models.ServiceResult<AdventureWorksDemo.Data.Models.Produ" +
                                "ctCategoryModel>"});
#line 67
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table170, "Then ");
#line hidden
                global::Reqnroll.Table table171 = new global::Reqnroll.Table(new string[] {
                            "IsFailure",
                            "IsSuccess",
                            "Message"});
                table171.AddRow(new string[] {
                            "False",
                            "True",
                            ""});
#line 70
 await testRunner.AndAsync("the result is", ((string)(null)), table171, "And ");
#line hidden
                global::Reqnroll.Table table172 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table172.AddRow(new string[] {
                            "1001",
                            "42",
                            "PingPong",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-0000-0000-000000000002"});
#line 73
 await testRunner.AndAsync("the results property \'Value\' contains", ((string)(null)), table172, "And ");
#line hidden
                global::Reqnroll.Table table173 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table173.AddRow(new string[] {
                            "41",
                            "4",
                            "Tires and Tubes",
                            "6/1/2002 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-60e28d47dcdf"});
                table173.AddRow(new string[] {
                            "42",
                            "",
                            "Record to Delete",
                            "6/1/2005 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-000000000001"});
                table173.AddRow(new string[] {
                            "1001",
                            "42",
                            "PingPong",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-0000-0000-000000000002"});
#line 76
 await testRunner.AndAsync("the table \'SalesLT.ProductCategory\' filtered by \'ProductCategoryId > 40\' contains" +
                        "", ((string)(null)), table173, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AddAsyncParentShortName")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceAddTests")]
        public async System.Threading.Tasks.Task AddAsyncParentShortName()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("AddAsyncParentShortName", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 82
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 83
 await testRunner.GivenAsync("I reset the database after the scenario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table174 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "ParentProductCategoryId",
                            "Rowguid"});
                table174.AddRow(new string[] {
                            "Hi",
                            "42",
                            "00000000-1111-0000-0000-000000000002"});
#line 84
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Models.ProductCategoryModel\'", ((string)(null)), table174, "When ");
#line hidden
                global::Reqnroll.Table table175 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table175.AddRow(new string[] {
                            "model",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Models.ProductCategoryModel"});
#line 87
 await testRunner.AndAsync("I call the method \'AddAsync\' with the parameter values", ((string)(null)), table175, "And ");
#line hidden
                global::Reqnroll.Table table176 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table176.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Models.ServiceResult<AdventureWorksDemo.Data.Models.Produ" +
                                "ctCategoryModel>"});
#line 90
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table176, "Then ");
#line hidden
                global::Reqnroll.Table table177 = new global::Reqnroll.Table(new string[] {
                            "IsFailure",
                            "IsSuccess",
                            "Message"});
                table177.AddRow(new string[] {
                            "True",
                            "False",
                            "\'Name\' must be between 3 and 50 characters. You entered 2 characters."});
#line 93
 await testRunner.AndAsync("the result is", ((string)(null)), table177, "And ");
#line hidden
                global::Reqnroll.Table table178 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table178.AddRow(new string[] {
                            "0",
                            "42",
                            "Hi",
                            "1/1/0001 12:00:00 AM",
                            "00000000-1111-0000-0000-000000000002"});
#line 97
 await testRunner.AndAsync("the results property \'Value\' contains", ((string)(null)), table178, "And ");
#line hidden
                global::Reqnroll.Table table179 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table179.AddRow(new string[] {
                            "41",
                            "4",
                            "Tires and Tubes",
                            "6/1/2002 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-60e28d47dcdf"});
                table179.AddRow(new string[] {
                            "42",
                            "",
                            "Record to Delete",
                            "6/1/2005 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-000000000001"});
#line 100
 await testRunner.AndAsync("the table \'SalesLT.ProductCategory\' filtered by \'ProductCategoryId > 40\' contains" +
                        "", ((string)(null)), table179, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AddBatchAsync")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceAddTests")]
        public async System.Threading.Tasks.Task AddBatchAsync()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("AddBatchAsync", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 105
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 106
 await testRunner.GivenAsync("I reset the database after the scenario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table180 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "ParentProductCategoryId",
                            "Rowguid"});
                table180.AddRow(new string[] {
                            "How",
                            "4",
                            "00000000-1111-1111-0000-000000000001"});
                table180.AddRow(new string[] {
                            "Now",
                            "5",
                            "00000000-1111-1111-0000-000000000002"});
                table180.AddRow(new string[] {
                            "Brown",
                            "41",
                            "00000000-1111-1111-0000-000000000003"});
                table180.AddRow(new string[] {
                            "Cow",
                            "",
                            "00000000-1111-1111-0000-000000000004"});
#line 107
 await testRunner.WhenAsync("I populate a list of the model \'AdventureWorksDemo.Data.Models.ProductCategoryMod" +
                        "el\'", ((string)(null)), table180, "When ");
#line hidden
                global::Reqnroll.Table table181 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table181.AddRow(new string[] {
                            "model",
                            "{{ListOfObjects}}",
                            "System.Collections.Generic.IEnumerable<AdventureWorksDemo.Data.Models.ProductCate" +
                                "goryModel>"});
#line 113
 await testRunner.AndAsync("I call the method \'AddBatchAsync\' with the parameter values", ((string)(null)), table181, "And ");
#line hidden
                global::Reqnroll.Table table182 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table182.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Models.ServiceResult<System.Collections.Generic.IEnumerab" +
                                "le<AdventureWorksDemo.Data.Models.ProductCategoryModel>"});
#line 116
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table182, "Then ");
#line hidden
                global::Reqnroll.Table table183 = new global::Reqnroll.Table(new string[] {
                            "IsFailure",
                            "IsSuccess",
                            "Message"});
                table183.AddRow(new string[] {
                            "false",
                            "true",
                            ""});
#line 119
 await testRunner.AndAsync("the result is", ((string)(null)), table183, "And ");
#line hidden
                global::Reqnroll.Table table184 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table184.AddRow(new string[] {
                            "1001",
                            "4",
                            "How",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-1111-0000-000000000001"});
                table184.AddRow(new string[] {
                            "1002",
                            "5",
                            "Now",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-1111-0000-000000000002"});
                table184.AddRow(new string[] {
                            "1003",
                            "41",
                            "Brown",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-1111-0000-000000000003"});
                table184.AddRow(new string[] {
                            "1004",
                            "",
                            "Cow",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-1111-0000-000000000004"});
#line 123
 await testRunner.AndAsync("the results property \'Value\' contains", ((string)(null)), table184, "And ");
#line hidden
                global::Reqnroll.Table table185 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table185.AddRow(new string[] {
                            "41",
                            "4",
                            "Tires and Tubes",
                            "6/1/2002 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-60e28d47dcdf"});
                table185.AddRow(new string[] {
                            "42",
                            "",
                            "Record to Delete",
                            "6/1/2005 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-000000000001"});
                table185.AddRow(new string[] {
                            "1001",
                            "4",
                            "How",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-1111-0000-000000000001"});
                table185.AddRow(new string[] {
                            "1002",
                            "5",
                            "Now",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-1111-0000-000000000002"});
                table185.AddRow(new string[] {
                            "1003",
                            "41",
                            "Brown",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-1111-0000-000000000003"});
                table185.AddRow(new string[] {
                            "1004",
                            "",
                            "Cow",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-1111-0000-000000000004"});
#line 130
 await testRunner.AndAsync("the table \'SalesLT.ProductCategory\' filtered by \'ProductCategoryId > 40\' contains" +
                        "", ((string)(null)), table185, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AddBatchAsync2ShortName")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceAddTests")]
        public async System.Threading.Tasks.Task AddBatchAsync2ShortName()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("AddBatchAsync2ShortName", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 139
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 140
 await testRunner.GivenAsync("I reset the database after the scenario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table186 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "ParentProductCategoryId",
                            "Rowguid"});
                table186.AddRow(new string[] {
                            "Hi",
                            "4",
                            "00000000-1111-1111-0000-000000000001"});
                table186.AddRow(new string[] {
                            "Now",
                            "5",
                            "00000000-1111-1111-0000-000000000002"});
                table186.AddRow(new string[] {
                            "Brown",
                            "41",
                            "00000000-1111-1111-0000-000000000003"});
                table186.AddRow(new string[] {
                            "It",
                            "",
                            "00000000-1111-1111-0000-000000000004"});
#line 141
 await testRunner.WhenAsync("I populate a list of the model \'AdventureWorksDemo.Data.Models.ProductCategoryMod" +
                        "el\'", ((string)(null)), table186, "When ");
#line hidden
                global::Reqnroll.Table table187 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table187.AddRow(new string[] {
                            "model",
                            "{{ListOfObjects}}",
                            "System.Collections.Generic.IEnumerable<AdventureWorksDemo.Data.Models.ProductCate" +
                                "goryModel>"});
#line 147
 await testRunner.AndAsync("I call the method \'AddBatchAsync\' with the parameter values", ((string)(null)), table187, "And ");
#line hidden
                global::Reqnroll.Table table188 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table188.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Models.ServiceResult<System.Collections.Generic.IEnumerab" +
                                "le<AdventureWorksDemo.Data.Models.ProductCategoryModel>"});
#line 150
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table188, "Then ");
#line hidden
                global::Reqnroll.Table table189 = new global::Reqnroll.Table(new string[] {
                            "IsFailure",
                            "IsSuccess"});
                table189.AddRow(new string[] {
                            "True",
                            "False"});
#line 153
 await testRunner.AndAsync("the result is", ((string)(null)), table189, "And ");
#line hidden
                global::Reqnroll.Table table190 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table190.AddRow(new string[] {
                            "\'Name\' must be between 3 and 50 characters. You entered 2 characters."});
                table190.AddRow(new string[] {
                            "\'Name\' must be between 3 and 50 characters. You entered 2 characters."});
#line 156
 await testRunner.AndAsync("the results property \'Message\' contains", ((string)(null)), table190, "And ");
#line hidden
                global::Reqnroll.Table table191 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table191.AddRow(new string[] {
                            "0",
                            "4",
                            "Hi",
                            "1/1/0001 12:00:00 AM",
                            "00000000-1111-1111-0000-000000000001"});
                table191.AddRow(new string[] {
                            "0",
                            "5",
                            "Now",
                            "1/1/0001 12:00:00 AM",
                            "00000000-1111-1111-0000-000000000002"});
                table191.AddRow(new string[] {
                            "0",
                            "41",
                            "Brown",
                            "1/1/0001 12:00:00 AM",
                            "00000000-1111-1111-0000-000000000003"});
                table191.AddRow(new string[] {
                            "0",
                            "",
                            "It",
                            "1/1/0001 12:00:00 AM",
                            "00000000-1111-1111-0000-000000000004"});
#line 160
 await testRunner.AndAsync("the results property \'Value\' contains", ((string)(null)), table191, "And ");
#line hidden
                global::Reqnroll.Table table192 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table192.AddRow(new string[] {
                            "41",
                            "4",
                            "Tires and Tubes",
                            "6/1/2002 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-60e28d47dcdf"});
                table192.AddRow(new string[] {
                            "42",
                            "",
                            "Record to Delete",
                            "6/1/2005 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-000000000001"});
#line 167
 await testRunner.AndAsync("the table \'SalesLT.ProductCategory\' filtered by \'ProductCategoryId > 40\' contains" +
                        "", ((string)(null)), table192, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
