// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AdventureWorksDemo.Data.Tests.reqnroll.Features.Services.ProductCategoryService
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ProductCategoryServiceFindTestsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Services/ProductCategoryService", "ProductCategoryServiceFindTests", "System tests for the ProductCategoryService\r\nTesting the methods FindAsync and Fi" +
                "ndAllAsync", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "ProductCategoryServiceFindTests.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
#line hidden
#line 8
 await testRunner.GivenAsync("The service to test is \'AdventureWorksDemo.Data.Services.IProductCategoryService\'" +
                    "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAsync01")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceFindTests")]
        public async System.Threading.Tasks.Task FindAsync01()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("FindAsync01", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table203 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table203.AddRow(new string[] {
                            "productCategoryId",
                            "1",
                            "int"});
#line 11
 await testRunner.WhenAsync("I call the method \'FindAsync\' with the parameter values", ((string)(null)), table203, "When ");
#line hidden
                global::Reqnroll.Table table204 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table204.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Models.ProductCategoryModel"});
#line 14
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table204, "Then ");
#line hidden
                global::Reqnroll.Table table205 = new global::Reqnroll.Table(new string[] {
                            "ModifiedDate",
                            "Name",
                            "ParentProductCategoryId",
                            "ProductCategoryId",
                            "Rowguid"});
                table205.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Bikes",
                            "",
                            "1",
                            "cfbda25c-df71-47a7-b81b-64ee161aa37c"});
#line 17
 await testRunner.AndAsync("the result is", ((string)(null)), table205, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAsync04")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceFindTests")]
        public async System.Threading.Tasks.Task FindAsync04()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("FindAsync04", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table206 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table206.AddRow(new string[] {
                            "productCategoryId",
                            "4",
                            "int"});
#line 22
 await testRunner.WhenAsync("I call the method \'FindAsync\' with the parameter values", ((string)(null)), table206, "When ");
#line hidden
                global::Reqnroll.Table table207 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table207.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Models.ProductCategoryModel"});
#line 25
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table207, "Then ");
#line hidden
                global::Reqnroll.Table table208 = new global::Reqnroll.Table(new string[] {
                            "ModifiedDate",
                            "Name",
                            "ParentProductCategoryId",
                            "ProductCategoryId",
                            "Rowguid"});
                table208.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Accessories",
                            "",
                            "4",
                            "2be3be36-d9a2-4eee-b593-ed895d97c2a6"});
#line 28
 await testRunner.AndAsync("the result is", ((string)(null)), table208, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAsync1234")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceFindTests")]
        public async System.Threading.Tasks.Task FindAsync1234()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("FindAsync1234", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table209 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table209.AddRow(new string[] {
                            "productCategoryId",
                            "1234",
                            "int"});
#line 33
 await testRunner.WhenAsync("I call the method \'FindAsync\' with the parameter values", ((string)(null)), table209, "When ");
#line hidden
                global::Reqnroll.Table table210 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table210.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Models.ProductCategoryModel"});
#line 37
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table210, "Then ");
#line hidden
#line 40
 await testRunner.AndAsync("the result is null", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAllAsync_1_5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceFindTests")]
        public async System.Threading.Tasks.Task FindAllAsync_1_5()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("FindAllAsync_1_5", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table211 = new global::Reqnroll.Table(new string[] {
                            "PageNumber",
                            "PageSize"});
                table211.AddRow(new string[] {
                            "1",
                            "5"});
#line 43
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Paging.PagingFilter\'", ((string)(null)), table211, "When ");
#line hidden
                global::Reqnroll.Table table212 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table212.AddRow(new string[] {
                            "pageingFilter",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Paging.PagingFilter"});
#line 46
 await testRunner.AndAsync("I call the method \'FindAllAsync\' with the parameter values", ((string)(null)), table212, "And ");
#line hidden
                global::Reqnroll.Table table213 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table213.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Paging.PagedList<AdventureWorksDemo.Data.Models.ProductCa" +
                                "tegoryModel>"});
#line 49
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table213, "Then ");
#line hidden
                global::Reqnroll.Table table214 = new global::Reqnroll.Table(new string[] {
                            "TotalPages",
                            "TotalCount",
                            "PageSize",
                            "CurrentPage",
                            "Count",
                            "Capacity"});
                table214.AddRow(new string[] {
                            "9",
                            "42",
                            "5",
                            "1",
                            "5",
                            "5"});
#line 52
 await testRunner.AndAsync("the PagedList values are", ((string)(null)), table214, "And ");
#line hidden
                global::Reqnroll.Table table215 = new global::Reqnroll.Table(new string[] {
                            "ModifiedDate",
                            "Name",
                            "ParentProductCategoryId",
                            "ProductCategoryId",
                            "Rowguid"});
                table215.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Accessories",
                            "",
                            "4",
                            "2be3be36-d9a2-4eee-b593-ed895d97c2a6"});
                table215.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Bikes",
                            "",
                            "1",
                            "cfbda25c-df71-47a7-b81b-64ee161aa37c"});
                table215.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Components",
                            "",
                            "2",
                            "c657828d-d808-4aba-91a3-af2ce02300e9"});
                table215.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Clothing",
                            "",
                            "3",
                            "10a7c342-ca82-48d4-8a38-46a2eb089b74"});
                table215.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Mountain Bikes",
                            "1",
                            "5",
                            "2d364ade-264a-433c-b092-4fcbf3804e01"});
#line 55
 await testRunner.AndAsync("the results are", ((string)(null)), table215, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAllAsync_1_500")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceFindTests")]
        public async System.Threading.Tasks.Task FindAllAsync_1_500()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("FindAllAsync_1_500", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 63
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table216 = new global::Reqnroll.Table(new string[] {
                            "PageNumber",
                            "PageSize"});
                table216.AddRow(new string[] {
                            "1",
                            "500"});
#line 64
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Paging.PagingFilter\'", ((string)(null)), table216, "When ");
#line hidden
                global::Reqnroll.Table table217 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table217.AddRow(new string[] {
                            "pageingFilter",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Paging.PagingFilter"});
#line 67
 await testRunner.AndAsync("I call the method \'FindAllAsync\' with the parameter values", ((string)(null)), table217, "And ");
#line hidden
                global::Reqnroll.Table table218 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table218.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Paging.PagedList<AdventureWorksDemo.Data.Models.ProductCa" +
                                "tegoryModel>"});
#line 70
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table218, "Then ");
#line hidden
                global::Reqnroll.Table table219 = new global::Reqnroll.Table(new string[] {
                            "TotalPages",
                            "TotalCount",
                            "PageSize",
                            "CurrentPage",
                            "Count",
                            "Capacity"});
                table219.AddRow(new string[] {
                            "1",
                            "42",
                            "100",
                            "1",
                            "42",
                            "42"});
#line 73
 await testRunner.AndAsync("the PagedList values are", ((string)(null)), table219, "And ");
#line hidden
                global::Reqnroll.Table table220 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table220.AddRow(new string[] {
                            "1",
                            "",
                            "Bikes",
                            "6/1/2002 12:00:00 AM",
                            "cfbda25c-df71-47a7-b81b-64ee161aa37c"});
                table220.AddRow(new string[] {
                            "2",
                            "",
                            "Components",
                            "6/1/2002 12:00:00 AM",
                            "c657828d-d808-4aba-91a3-af2ce02300e9"});
                table220.AddRow(new string[] {
                            "3",
                            "",
                            "Clothing",
                            "6/1/2002 12:00:00 AM",
                            "10a7c342-ca82-48d4-8a38-46a2eb089b74"});
                table220.AddRow(new string[] {
                            "4",
                            "",
                            "Accessories",
                            "6/1/2002 12:00:00 AM",
                            "2be3be36-d9a2-4eee-b593-ed895d97c2a6"});
                table220.AddRow(new string[] {
                            "5",
                            "1",
                            "Mountain Bikes",
                            "6/1/2002 12:00:00 AM",
                            "2d364ade-264a-433c-b092-4fcbf3804e01"});
                table220.AddRow(new string[] {
                            "6",
                            "1",
                            "Road Bikes",
                            "6/1/2002 12:00:00 AM",
                            "000310c0-bcc8-42c4-b0c3-45ae611af06b"});
                table220.AddRow(new string[] {
                            "7",
                            "1",
                            "Touring Bikes",
                            "6/1/2002 12:00:00 AM",
                            "02c5061d-ecdc-4274-b5f1-e91d76bc3f37"});
                table220.AddRow(new string[] {
                            "8",
                            "2",
                            "Handlebars",
                            "6/1/2002 12:00:00 AM",
                            "3ef2c725-7135-4c85-9ae6-ae9a3bdd9283"});
                table220.AddRow(new string[] {
                            "9",
                            "2",
                            "Bottom Brackets",
                            "6/1/2002 12:00:00 AM",
                            "a9e54089-8a1e-4cf5-8646-e3801f685934"});
                table220.AddRow(new string[] {
                            "10",
                            "2",
                            "Brakes",
                            "6/1/2002 12:00:00 AM",
                            "d43ba4a3-ef0d-426b-90eb-4be4547dd30c"});
                table220.AddRow(new string[] {
                            "11",
                            "2",
                            "Chains",
                            "6/1/2002 12:00:00 AM",
                            "e93a7231-f16c-4b0f-8c41-c73fdec62da0"});
                table220.AddRow(new string[] {
                            "12",
                            "2",
                            "Cranksets",
                            "6/1/2002 12:00:00 AM",
                            "4f644521-422b-4f19-974a-e3df6102567e"});
                table220.AddRow(new string[] {
                            "13",
                            "2",
                            "Derailleurs",
                            "6/1/2002 12:00:00 AM",
                            "1830d70c-aa2a-40c0-a271-5ba86f38f8bf"});
                table220.AddRow(new string[] {
                            "14",
                            "2",
                            "Forks",
                            "6/1/2002 12:00:00 AM",
                            "b5f9ba42-b69b-4fdd-b2ec-57fb7b42e3cf"});
                table220.AddRow(new string[] {
                            "15",
                            "2",
                            "Headsets",
                            "6/1/2002 12:00:00 AM",
                            "7c782bbe-5a16-495a-aa50-10afe5a84af2"});
                table220.AddRow(new string[] {
                            "16",
                            "2",
                            "Mountain Frames",
                            "6/1/2002 12:00:00 AM",
                            "61b21b65-e16a-4be7-9300-4d8e9db861be"});
                table220.AddRow(new string[] {
                            "17",
                            "2",
                            "Pedals",
                            "6/1/2002 12:00:00 AM",
                            "6d24ac07-7a84-4849-864a-865a14125bc9"});
                table220.AddRow(new string[] {
                            "18",
                            "2",
                            "Road Frames",
                            "6/1/2002 12:00:00 AM",
                            "5515f857-075b-4f9a-87b7-43b4997077b3"});
                table220.AddRow(new string[] {
                            "19",
                            "2",
                            "Saddles",
                            "6/1/2002 12:00:00 AM",
                            "049fffa3-9d30-46df-82f7-f20730ec02b3"});
                table220.AddRow(new string[] {
                            "20",
                            "2",
                            "Touring Frames",
                            "6/1/2002 12:00:00 AM",
                            "d2e3f1a8-56c4-4f36-b29d-5659fc0d2789"});
                table220.AddRow(new string[] {
                            "21",
                            "2",
                            "Wheels",
                            "6/1/2002 12:00:00 AM",
                            "43521287-4b0b-438e-b80e-d82d9ad7c9f0"});
                table220.AddRow(new string[] {
                            "22",
                            "3",
                            "Bib-Shorts",
                            "6/1/2002 12:00:00 AM",
                            "67b58d2b-5798-4a90-8c6c-5ddacf057171"});
                table220.AddRow(new string[] {
                            "23",
                            "3",
                            "Caps",
                            "6/1/2002 12:00:00 AM",
                            "430dd6a8-a755-4b23-bb05-52520107da5f"});
                table220.AddRow(new string[] {
                            "24",
                            "3",
                            "Gloves",
                            "6/1/2002 12:00:00 AM",
                            "92d5657b-0032-4e49-bad5-41a441a70942"});
                table220.AddRow(new string[] {
                            "25",
                            "3",
                            "Jerseys",
                            "6/1/2002 12:00:00 AM",
                            "09e91437-ba4f-4b1a-8215-74184fd95db8"});
                table220.AddRow(new string[] {
                            "26",
                            "3",
                            "Shorts",
                            "6/1/2002 12:00:00 AM",
                            "1a5ba5b3-03c3-457c-b11e-4fa85ede87da"});
                table220.AddRow(new string[] {
                            "27",
                            "3",
                            "Socks",
                            "6/1/2002 12:00:00 AM",
                            "701019c3-09fe-4949-8386-c6ce686474e5"});
                table220.AddRow(new string[] {
                            "28",
                            "3",
                            "Tights",
                            "6/1/2002 12:00:00 AM",
                            "5deb3e55-9897-4416-b18a-515e970bc2d1"});
                table220.AddRow(new string[] {
                            "29",
                            "3",
                            "Vests",
                            "6/1/2002 12:00:00 AM",
                            "9ad7fe93-5ba0-4736-b578-ff80a2071297"});
                table220.AddRow(new string[] {
                            "30",
                            "4",
                            "Bike Racks",
                            "6/1/2002 12:00:00 AM",
                            "4624b5ce-66d6-496b-9201-c053df3556cc"});
                table220.AddRow(new string[] {
                            "31",
                            "4",
                            "Bike Stands",
                            "6/1/2002 12:00:00 AM",
                            "43b445c8-b820-424e-a1d5-90d81da0b46f"});
                table220.AddRow(new string[] {
                            "32",
                            "4",
                            "Bottles and Cages",
                            "6/1/2002 12:00:00 AM",
                            "9b7dff41-9fa3-4776-8def-2c9a48c8b779"});
                table220.AddRow(new string[] {
                            "33",
                            "4",
                            "Cleaners",
                            "6/1/2002 12:00:00 AM",
                            "9ad3bcf0-244d-4ec4-a6a0-fb701351c6a3"});
                table220.AddRow(new string[] {
                            "34",
                            "4",
                            "Fenders",
                            "6/1/2002 12:00:00 AM",
                            "1697f8a2-0a08-4883-b7dd-d19117b4e9a7"});
                table220.AddRow(new string[] {
                            "35",
                            "4",
                            "Helmets",
                            "6/1/2002 12:00:00 AM",
                            "f5e07a33-c9e0-439c-b5f3-9f25fb65becc"});
                table220.AddRow(new string[] {
                            "36",
                            "4",
                            "Hydration Packs",
                            "6/1/2002 12:00:00 AM",
                            "646a8906-fc87-4267-a443-9c6d791e6693"});
                table220.AddRow(new string[] {
                            "37",
                            "4",
                            "Lights",
                            "6/1/2002 12:00:00 AM",
                            "954178ba-624f-42db-95f6-ca035f36d130"});
                table220.AddRow(new string[] {
                            "38",
                            "4",
                            "Locks",
                            "6/1/2002 12:00:00 AM",
                            "19646983-3fa0-4773-9a0c-f34c49df9bc8"});
                table220.AddRow(new string[] {
                            "39",
                            "4",
                            "Panniers",
                            "6/1/2002 12:00:00 AM",
                            "3002a5d5-fec3-464b-bef3-e0f81d35f431"});
                table220.AddRow(new string[] {
                            "40",
                            "4",
                            "Pumps",
                            "6/1/2002 12:00:00 AM",
                            "fe4d46f2-c87c-48c5-a4a1-3f55712d80b1"});
                table220.AddRow(new string[] {
                            "41",
                            "4",
                            "Tires and Tubes",
                            "6/1/2002 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-60e28d47dcdf"});
                table220.AddRow(new string[] {
                            "42",
                            "",
                            "Record to Delete",
                            "6/1/2005 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-000000000001"});
#line 76
 await testRunner.AndAsync("the results are", ((string)(null)), table220, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAllAsync_2_5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceFindTests")]
        public async System.Threading.Tasks.Task FindAllAsync_2_5()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("FindAllAsync_2_5", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 120
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table221 = new global::Reqnroll.Table(new string[] {
                            "PageNumber",
                            "PageSize"});
                table221.AddRow(new string[] {
                            "2",
                            "5"});
#line 121
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Paging.PagingFilter\'", ((string)(null)), table221, "When ");
#line hidden
                global::Reqnroll.Table table222 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table222.AddRow(new string[] {
                            "pageingFilter",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Paging.PagingFilter"});
#line 124
 await testRunner.AndAsync("I call the method \'FindAllAsync\' with the parameter values", ((string)(null)), table222, "And ");
#line hidden
                global::Reqnroll.Table table223 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table223.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Paging.PagedList<AdventureWorksDemo.Data.Models.ProductCa" +
                                "tegoryModel>"});
#line 127
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table223, "Then ");
#line hidden
                global::Reqnroll.Table table224 = new global::Reqnroll.Table(new string[] {
                            "TotalPages",
                            "TotalCount",
                            "PageSize",
                            "CurrentPage",
                            "Count",
                            "Capacity"});
                table224.AddRow(new string[] {
                            "9",
                            "42",
                            "5",
                            "2",
                            "5",
                            "5"});
#line 130
 await testRunner.AndAsync("the PagedList values are", ((string)(null)), table224, "And ");
#line hidden
                global::Reqnroll.Table table225 = new global::Reqnroll.Table(new string[] {
                            "ModifiedDate",
                            "Name",
                            "ParentProductCategoryId",
                            "ProductCategoryId",
                            "Rowguid"});
                table225.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Road Bikes",
                            "1",
                            "6",
                            "000310c0-bcc8-42c4-b0c3-45ae611af06b"});
                table225.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Touring Bikes",
                            "1",
                            "7",
                            "02c5061d-ecdc-4274-b5f1-e91d76bc3f37"});
                table225.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Handlebars",
                            "2",
                            "8",
                            "3ef2c725-7135-4c85-9ae6-ae9a3bdd9283"});
                table225.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Bottom Brackets",
                            "2",
                            "9",
                            "a9e54089-8a1e-4cf5-8646-e3801f685934"});
                table225.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Brakes",
                            "2",
                            "10",
                            "d43ba4a3-ef0d-426b-90eb-4be4547dd30c"});
#line 133
 await testRunner.AndAsync("the results are", ((string)(null)), table225, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAllAsync_2_8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceFindTests")]
        public async System.Threading.Tasks.Task FindAllAsync_2_8()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("FindAllAsync_2_8", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 141
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table226 = new global::Reqnroll.Table(new string[] {
                            "PageNumber",
                            "PageSize"});
                table226.AddRow(new string[] {
                            "2",
                            "8"});
#line 142
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Paging.PagingFilter\'", ((string)(null)), table226, "When ");
#line hidden
                global::Reqnroll.Table table227 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table227.AddRow(new string[] {
                            "pageingFilter",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Paging.PagingFilter"});
#line 145
 await testRunner.AndAsync("I call the method \'FindAllAsync\' with the parameter values", ((string)(null)), table227, "And ");
#line hidden
                global::Reqnroll.Table table228 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table228.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Paging.PagedList<AdventureWorksDemo.Data.Models.ProductCa" +
                                "tegoryModel>"});
#line 148
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table228, "Then ");
#line hidden
                global::Reqnroll.Table table229 = new global::Reqnroll.Table(new string[] {
                            "TotalPages",
                            "TotalCount",
                            "PageSize",
                            "CurrentPage",
                            "Count",
                            "Capacity"});
                table229.AddRow(new string[] {
                            "6",
                            "42",
                            "8",
                            "2",
                            "8",
                            "8"});
#line 151
 await testRunner.AndAsync("the PagedList values are", ((string)(null)), table229, "And ");
#line hidden
                global::Reqnroll.Table table230 = new global::Reqnroll.Table(new string[] {
                            "ModifiedDate",
                            "Name",
                            "ParentProductCategoryId",
                            "ProductCategoryId",
                            "Rowguid"});
                table230.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Bottom Brackets",
                            "2",
                            "9",
                            "a9e54089-8a1e-4cf5-8646-e3801f685934"});
                table230.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Brakes",
                            "2",
                            "10",
                            "d43ba4a3-ef0d-426b-90eb-4be4547dd30c"});
                table230.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Chains",
                            "2",
                            "11",
                            "e93a7231-f16c-4b0f-8c41-c73fdec62da0"});
                table230.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Cranksets",
                            "2",
                            "12",
                            "4f644521-422b-4f19-974a-e3df6102567e"});
                table230.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Derailleurs",
                            "2",
                            "13",
                            "1830d70c-aa2a-40c0-a271-5ba86f38f8bf"});
                table230.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Forks",
                            "2",
                            "14",
                            "b5f9ba42-b69b-4fdd-b2ec-57fb7b42e3cf"});
                table230.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Headsets",
                            "2",
                            "15",
                            "7c782bbe-5a16-495a-aa50-10afe5a84af2"});
                table230.AddRow(new string[] {
                            "6/1/2002 12:00:00 AM",
                            "Mountain Frames",
                            "2",
                            "16",
                            "61b21b65-e16a-4be7-9300-4d8e9db861be"});
#line 154
 await testRunner.AndAsync("the results are", ((string)(null)), table230, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAllAsync_1234_5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceFindTests")]
        public async System.Threading.Tasks.Task FindAllAsync_1234_5()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("FindAllAsync_1234_5", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 165
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table231 = new global::Reqnroll.Table(new string[] {
                            "PageNumber",
                            "PageSize"});
                table231.AddRow(new string[] {
                            "1234",
                            "5"});
#line 166
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Paging.PagingFilter\'", ((string)(null)), table231, "When ");
#line hidden
                global::Reqnroll.Table table232 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table232.AddRow(new string[] {
                            "pageingFilter",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Paging.PagingFilter"});
#line 169
 await testRunner.AndAsync("I call the method \'FindAllAsync\' with the parameter values", ((string)(null)), table232, "And ");
#line hidden
                global::Reqnroll.Table table233 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table233.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Paging.PagedList<AdventureWorksDemo.Data.Models.ProductCa" +
                                "tegoryModel>"});
#line 172
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table233, "Then ");
#line hidden
                global::Reqnroll.Table table234 = new global::Reqnroll.Table(new string[] {
                            "TotalPages",
                            "TotalCount",
                            "PageSize",
                            "CurrentPage",
                            "Count",
                            "Capacity"});
                table234.AddRow(new string[] {
                            "9",
                            "42",
                            "5",
                            "1234",
                            "0",
                            "0"});
#line 175
 await testRunner.AndAsync("the PagedList values are", ((string)(null)), table234, "And ");
#line hidden
                global::Reqnroll.Table table235 = new global::Reqnroll.Table(new string[] {
                            "ModifiedDate",
                            "Name",
                            "ParentProductCategoryId",
                            "ProductCategoryId",
                            "Rowguid"});
#line 178
 await testRunner.AndAsync("the results are", ((string)(null)), table235, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAllAsync_0_5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceFindTests")]
        public async System.Threading.Tasks.Task FindAllAsync_0_5()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("FindAllAsync_0_5", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 181
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table236 = new global::Reqnroll.Table(new string[] {
                            "PageNumber",
                            "PageSize"});
                table236.AddRow(new string[] {
                            "0",
                            "5"});
#line 182
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Paging.PagingFilter\'", ((string)(null)), table236, "When ");
#line hidden
                global::Reqnroll.Table table237 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table237.AddRow(new string[] {
                            "pageingFilter",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Paging.PagingFilter"});
#line 185
 await testRunner.AndAsync("I call the method \'FindAllAsync\' with the parameter values", ((string)(null)), table237, "And ");
#line hidden
                global::Reqnroll.Table table238 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table238.AddRow(new string[] {
                            "System.ArgumentOutOfRangeException"});
#line 188
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table238, "Then ");
#line hidden
                global::Reqnroll.Table table239 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table239.AddRow(new string[] {
                            "Parameter pageNumber must be positive (Parameter \'pageNumber\')"});
#line 191
 await testRunner.AndAsync("the exception message is", ((string)(null)), table239, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAllAsync_0_0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceFindTests")]
        public async System.Threading.Tasks.Task FindAllAsync_0_0()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("FindAllAsync_0_0", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 195
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table240 = new global::Reqnroll.Table(new string[] {
                            "PageNumber",
                            "PageSize"});
                table240.AddRow(new string[] {
                            "0",
                            "0"});
#line 196
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Paging.PagingFilter\'", ((string)(null)), table240, "When ");
#line hidden
                global::Reqnroll.Table table241 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table241.AddRow(new string[] {
                            "pageingFilter",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Paging.PagingFilter"});
#line 199
 await testRunner.AndAsync("I call the method \'FindAllAsync\' with the parameter values", ((string)(null)), table241, "And ");
#line hidden
                global::Reqnroll.Table table242 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table242.AddRow(new string[] {
                            "System.ArgumentOutOfRangeException"});
#line 202
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table242, "Then ");
#line hidden
                global::Reqnroll.Table table243 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table243.AddRow(new string[] {
                            "Parameter pageNumber must be positive (Parameter \'pageNumber\')"});
#line 205
 await testRunner.AndAsync("the exception message is", ((string)(null)), table243, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("FindAllAsync_5_0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceFindTests")]
        public async System.Threading.Tasks.Task FindAllAsync_5_0()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("FindAllAsync_5_0", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 209
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table244 = new global::Reqnroll.Table(new string[] {
                            "PageNumber",
                            "PageSize"});
                table244.AddRow(new string[] {
                            "5",
                            "0"});
#line 210
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Paging.PagingFilter\'", ((string)(null)), table244, "When ");
#line hidden
                global::Reqnroll.Table table245 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table245.AddRow(new string[] {
                            "pageingFilter",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Paging.PagingFilter"});
#line 213
 await testRunner.AndAsync("I call the method \'FindAllAsync\' with the parameter values", ((string)(null)), table245, "And ");
#line hidden
                global::Reqnroll.Table table246 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table246.AddRow(new string[] {
                            "System.ArgumentOutOfRangeException"});
#line 216
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table246, "Then ");
#line hidden
                global::Reqnroll.Table table247 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table247.AddRow(new string[] {
                            "Parameter pageSize must be positive (Parameter \'pageSize\')"});
#line 219
 await testRunner.AndAsync("the exception message is", ((string)(null)), table247, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
