// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AdventureWorksDemo.Data.Tests.reqnroll.Features.Services.ProductCategoryService
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ProductCategoryServiceAddTestsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Services/ProductCategoryService", "ProductCategoryServiceAddTests", "System tests for the ProductCategoryService\r\nTesting the methods AddAsync", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "ProductCategoryServiceAddTests.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
#line hidden
#line 9
 await testRunner.GivenAsync("The service to test is \'AdventureWorksDemo.Data.Services.IProductCategoryService\'" +
                    "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 10
 await testRunner.AndAsync("I don\'t reset the database after the scenario", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AddAsyncNoParent")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceAddTests")]
        public async System.Threading.Tasks.Task AddAsyncNoParent()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("AddAsyncNoParent", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 13
 await testRunner.GivenAsync("I reset the database after the scenario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table290 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "ParentProductCategoryId",
                            "Rowguid"});
                table290.AddRow(new string[] {
                            "PingPong",
                            "",
                            "00000000-1111-0000-0000-000000000002"});
#line 14
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Models.ProductCategoryModel\'", ((string)(null)), table290, "When ");
#line hidden
                global::Reqnroll.Table table291 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table291.AddRow(new string[] {
                            "model",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Models.ProductCategoryModel"});
#line 17
 await testRunner.AndAsync("I call the method \'AddAsync\' with the parameter values", ((string)(null)), table291, "And ");
#line hidden
                global::Reqnroll.Table table292 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table292.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Models.ServiceResult<AdventureWorksDemo.Data.Models.Produ" +
                                "ctCategoryModel>"});
#line 20
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table292, "Then ");
#line hidden
                global::Reqnroll.Table table293 = new global::Reqnroll.Table(new string[] {
                            "IsFailure",
                            "IsSuccess",
                            "Message"});
                table293.AddRow(new string[] {
                            "False",
                            "True",
                            ""});
#line 23
 await testRunner.AndAsync("the result is", ((string)(null)), table293, "And ");
#line hidden
                global::Reqnroll.Table table294 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table294.AddRow(new string[] {
                            "5001",
                            "",
                            "PingPong",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-0000-0000-000000000002"});
#line 26
 await testRunner.AndAsync("the results property \'Value\' contains", ((string)(null)), table294, "And ");
#line hidden
                global::Reqnroll.Table table295 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table295.AddRow(new string[] {
                            "41",
                            "4",
                            "Tires and Tubes",
                            "6/1/2002 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-60e28d47dcdf"});
                table295.AddRow(new string[] {
                            "42",
                            "",
                            "Record to Delete",
                            "6/1/2005 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-000000000001"});
                table295.AddRow(new string[] {
                            "5001",
                            "",
                            "PingPong",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-0000-0000-000000000002"});
#line 29
 await testRunner.AndAsync("the table \'SalesLT.ProductCategory\' filtered by \'ProductCategoryId > 40\' contains" +
                        "", ((string)(null)), table295, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AddAsyncNoParentShortName")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceAddTests")]
        public async System.Threading.Tasks.Task AddAsyncNoParentShortName()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("AddAsyncNoParentShortName", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 36
 await testRunner.GivenAsync("I reset the database after the scenario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table296 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "ParentProductCategoryId",
                            "Rowguid"});
                table296.AddRow(new string[] {
                            "Hi",
                            "",
                            "00000000-1111-0000-0000-000000000002"});
#line 37
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Models.ProductCategoryModel\'", ((string)(null)), table296, "When ");
#line hidden
                global::Reqnroll.Table table297 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table297.AddRow(new string[] {
                            "model",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Models.ProductCategoryModel"});
#line 40
 await testRunner.AndAsync("I call the method \'AddAsync\' with the parameter values", ((string)(null)), table297, "And ");
#line hidden
                global::Reqnroll.Table table298 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table298.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Models.ServiceResult<AdventureWorksDemo.Data.Models.Produ" +
                                "ctCategoryModel>"});
#line 43
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table298, "Then ");
#line hidden
                global::Reqnroll.Table table299 = new global::Reqnroll.Table(new string[] {
                            "IsFailure",
                            "IsSuccess",
                            "Message"});
                table299.AddRow(new string[] {
                            "True",
                            "False",
                            "\'Name\' must be between 3 and 50 characters. You entered 2 characters."});
#line 46
 await testRunner.AndAsync("the result is", ((string)(null)), table299, "And ");
#line hidden
                global::Reqnroll.Table table300 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table300.AddRow(new string[] {
                            "0",
                            "",
                            "Hi",
                            "1/1/0001 12:00:00 AM",
                            "00000000-1111-0000-0000-000000000002"});
#line 50
 await testRunner.AndAsync("the results property \'Value\' contains", ((string)(null)), table300, "And ");
#line hidden
                global::Reqnroll.Table table301 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table301.AddRow(new string[] {
                            "41",
                            "4",
                            "Tires and Tubes",
                            "6/1/2002 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-60e28d47dcdf"});
                table301.AddRow(new string[] {
                            "42",
                            "",
                            "Record to Delete",
                            "6/1/2005 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-000000000001"});
#line 54
 await testRunner.AndAsync("the table \'SalesLT.ProductCategory\' filtered by \'ProductCategoryId > 40\' contains" +
                        "", ((string)(null)), table301, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AddAsyncParent")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceAddTests")]
        public async System.Threading.Tasks.Task AddAsyncParent()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("AddAsyncParent", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 59
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 60
 await testRunner.GivenAsync("I reset the database after the scenario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table302 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "ParentProductCategoryId",
                            "Rowguid"});
                table302.AddRow(new string[] {
                            "PingPong",
                            "42",
                            "00000000-1111-0000-0000-000000000002"});
#line 61
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Models.ProductCategoryModel\'", ((string)(null)), table302, "When ");
#line hidden
                global::Reqnroll.Table table303 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table303.AddRow(new string[] {
                            "model",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Models.ProductCategoryModel"});
#line 64
 await testRunner.AndAsync("I call the method \'AddAsync\' with the parameter values", ((string)(null)), table303, "And ");
#line hidden
                global::Reqnroll.Table table304 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table304.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Models.ServiceResult<AdventureWorksDemo.Data.Models.Produ" +
                                "ctCategoryModel>"});
#line 67
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table304, "Then ");
#line hidden
                global::Reqnroll.Table table305 = new global::Reqnroll.Table(new string[] {
                            "IsFailure",
                            "IsSuccess",
                            "Message"});
                table305.AddRow(new string[] {
                            "False",
                            "True",
                            ""});
#line 70
 await testRunner.AndAsync("the result is", ((string)(null)), table305, "And ");
#line hidden
                global::Reqnroll.Table table306 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table306.AddRow(new string[] {
                            "5001",
                            "42",
                            "PingPong",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-0000-0000-000000000002"});
#line 73
 await testRunner.AndAsync("the results property \'Value\' contains", ((string)(null)), table306, "And ");
#line hidden
                global::Reqnroll.Table table307 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table307.AddRow(new string[] {
                            "41",
                            "4",
                            "Tires and Tubes",
                            "6/1/2002 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-60e28d47dcdf"});
                table307.AddRow(new string[] {
                            "42",
                            "",
                            "Record to Delete",
                            "6/1/2005 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-000000000001"});
                table307.AddRow(new string[] {
                            "5001",
                            "42",
                            "PingPong",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-0000-0000-000000000002"});
#line 76
 await testRunner.AndAsync("the table \'SalesLT.ProductCategory\' filtered by \'ProductCategoryId > 40\' contains" +
                        "", ((string)(null)), table307, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AddAsyncParentShortName")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceAddTests")]
        public async System.Threading.Tasks.Task AddAsyncParentShortName()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("AddAsyncParentShortName", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 82
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 83
 await testRunner.GivenAsync("I reset the database after the scenario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table308 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "ParentProductCategoryId",
                            "Rowguid"});
                table308.AddRow(new string[] {
                            "Hi",
                            "42",
                            "00000000-1111-0000-0000-000000000002"});
#line 84
 await testRunner.WhenAsync("I populate the model \'AdventureWorksDemo.Data.Models.ProductCategoryModel\'", ((string)(null)), table308, "When ");
#line hidden
                global::Reqnroll.Table table309 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table309.AddRow(new string[] {
                            "model",
                            "{{model}}",
                            "AdventureWorksDemo.Data.Models.ProductCategoryModel"});
#line 87
 await testRunner.AndAsync("I call the method \'AddAsync\' with the parameter values", ((string)(null)), table309, "And ");
#line hidden
                global::Reqnroll.Table table310 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table310.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Models.ServiceResult<AdventureWorksDemo.Data.Models.Produ" +
                                "ctCategoryModel>"});
#line 90
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table310, "Then ");
#line hidden
                global::Reqnroll.Table table311 = new global::Reqnroll.Table(new string[] {
                            "IsFailure",
                            "IsSuccess",
                            "Message"});
                table311.AddRow(new string[] {
                            "True",
                            "False",
                            "\'Name\' must be between 3 and 50 characters. You entered 2 characters."});
#line 93
 await testRunner.AndAsync("the result is", ((string)(null)), table311, "And ");
#line hidden
                global::Reqnroll.Table table312 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table312.AddRow(new string[] {
                            "0",
                            "42",
                            "Hi",
                            "1/1/0001 12:00:00 AM",
                            "00000000-1111-0000-0000-000000000002"});
#line 97
 await testRunner.AndAsync("the results property \'Value\' contains", ((string)(null)), table312, "And ");
#line hidden
                global::Reqnroll.Table table313 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table313.AddRow(new string[] {
                            "41",
                            "4",
                            "Tires and Tubes",
                            "6/1/2002 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-60e28d47dcdf"});
                table313.AddRow(new string[] {
                            "42",
                            "",
                            "Record to Delete",
                            "6/1/2005 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-000000000001"});
#line 100
 await testRunner.AndAsync("the table \'SalesLT.ProductCategory\' filtered by \'ProductCategoryId > 40\' contains" +
                        "", ((string)(null)), table313, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AddBatchAsync")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceAddTests")]
        public async System.Threading.Tasks.Task AddBatchAsync()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("AddBatchAsync", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 105
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 106
 await testRunner.GivenAsync("I reset the database after the scenario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table314 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "ParentProductCategoryId",
                            "Rowguid"});
                table314.AddRow(new string[] {
                            "How",
                            "4",
                            "00000000-1111-1111-0000-000000000001"});
                table314.AddRow(new string[] {
                            "Now",
                            "5",
                            "00000000-1111-1111-0000-000000000002"});
                table314.AddRow(new string[] {
                            "Brown",
                            "41",
                            "00000000-1111-1111-0000-000000000003"});
                table314.AddRow(new string[] {
                            "Cow",
                            "",
                            "00000000-1111-1111-0000-000000000004"});
#line 107
 await testRunner.WhenAsync("I populate a list of the model \'AdventureWorksDemo.Data.Models.ProductCategoryMod" +
                        "el\'", ((string)(null)), table314, "When ");
#line hidden
                global::Reqnroll.Table table315 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table315.AddRow(new string[] {
                            "model",
                            "{{ListOfObjects}}",
                            "System.Collections.Generic.IEnumerable<AdventureWorksDemo.Data.Models.ProductCate" +
                                "goryModel>"});
#line 113
 await testRunner.AndAsync("I call the method \'AddBatchAsync\' with the parameter values", ((string)(null)), table315, "And ");
#line hidden
                global::Reqnroll.Table table316 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table316.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Models.ServiceResult<System.Collections.Generic.IEnumerab" +
                                "le<AdventureWorksDemo.Data.Models.ProductCategoryModel>"});
#line 116
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table316, "Then ");
#line hidden
                global::Reqnroll.Table table317 = new global::Reqnroll.Table(new string[] {
                            "IsFailure",
                            "IsSuccess",
                            "Message"});
                table317.AddRow(new string[] {
                            "false",
                            "true",
                            ""});
#line 119
 await testRunner.AndAsync("the result is", ((string)(null)), table317, "And ");
#line hidden
                global::Reqnroll.Table table318 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table318.AddRow(new string[] {
                            "5001",
                            "4",
                            "How",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-1111-0000-000000000001"});
                table318.AddRow(new string[] {
                            "5002",
                            "5",
                            "Now",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-1111-0000-000000000002"});
                table318.AddRow(new string[] {
                            "5003",
                            "41",
                            "Brown",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-1111-0000-000000000003"});
                table318.AddRow(new string[] {
                            "5004",
                            "",
                            "Cow",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-1111-0000-000000000004"});
#line 123
 await testRunner.AndAsync("the results property \'Value\' contains", ((string)(null)), table318, "And ");
#line hidden
                global::Reqnroll.Table table319 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table319.AddRow(new string[] {
                            "41",
                            "4",
                            "Tires and Tubes",
                            "6/1/2002 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-60e28d47dcdf"});
                table319.AddRow(new string[] {
                            "42",
                            "",
                            "Record to Delete",
                            "6/1/2005 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-000000000001"});
                table319.AddRow(new string[] {
                            "5001",
                            "4",
                            "How",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-1111-0000-000000000001"});
                table319.AddRow(new string[] {
                            "5002",
                            "5",
                            "Now",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-1111-0000-000000000002"});
                table319.AddRow(new string[] {
                            "5003",
                            "41",
                            "Brown",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-1111-0000-000000000003"});
                table319.AddRow(new string[] {
                            "5004",
                            "",
                            "Cow",
                            "5/24/2024 12:34:56 PM",
                            "00000000-1111-1111-0000-000000000004"});
#line 130
 await testRunner.AndAsync("the table \'SalesLT.ProductCategory\' filtered by \'ProductCategoryId > 40\' contains" +
                        "", ((string)(null)), table319, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AddBatchAsync2ShortName")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProductCategoryServiceAddTests")]
        public async System.Threading.Tasks.Task AddBatchAsync2ShortName()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("AddBatchAsync2ShortName", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 139
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 140
 await testRunner.GivenAsync("I reset the database after the scenario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table320 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "ParentProductCategoryId",
                            "Rowguid"});
                table320.AddRow(new string[] {
                            "Hi",
                            "4",
                            "00000000-1111-1111-0000-000000000001"});
                table320.AddRow(new string[] {
                            "Now",
                            "5",
                            "00000000-1111-1111-0000-000000000002"});
                table320.AddRow(new string[] {
                            "Brown",
                            "41",
                            "00000000-1111-1111-0000-000000000003"});
                table320.AddRow(new string[] {
                            "It",
                            "",
                            "00000000-1111-1111-0000-000000000004"});
#line 141
 await testRunner.WhenAsync("I populate a list of the model \'AdventureWorksDemo.Data.Models.ProductCategoryMod" +
                        "el\'", ((string)(null)), table320, "When ");
#line hidden
                global::Reqnroll.Table table321 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value",
                            "TypeName"});
                table321.AddRow(new string[] {
                            "model",
                            "{{ListOfObjects}}",
                            "System.Collections.Generic.IEnumerable<AdventureWorksDemo.Data.Models.ProductCate" +
                                "goryModel>"});
#line 147
 await testRunner.AndAsync("I call the method \'AddBatchAsync\' with the parameter values", ((string)(null)), table321, "And ");
#line hidden
                global::Reqnroll.Table table322 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table322.AddRow(new string[] {
                            "AdventureWorksDemo.Data.Models.ServiceResult<System.Collections.Generic.IEnumerab" +
                                "le<AdventureWorksDemo.Data.Models.ProductCategoryModel>"});
#line 150
 await testRunner.ThenAsync("the result is of type", ((string)(null)), table322, "Then ");
#line hidden
                global::Reqnroll.Table table323 = new global::Reqnroll.Table(new string[] {
                            "IsFailure",
                            "IsSuccess"});
                table323.AddRow(new string[] {
                            "True",
                            "False"});
#line 153
 await testRunner.AndAsync("the result is", ((string)(null)), table323, "And ");
#line hidden
                global::Reqnroll.Table table324 = new global::Reqnroll.Table(new string[] {
                            "Expected"});
                table324.AddRow(new string[] {
                            "\'Name\' must be between 3 and 50 characters. You entered 2 characters."});
                table324.AddRow(new string[] {
                            "\'Name\' must be between 3 and 50 characters. You entered 2 characters."});
#line 156
 await testRunner.AndAsync("the results property \'Message\' contains", ((string)(null)), table324, "And ");
#line hidden
                global::Reqnroll.Table table325 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table325.AddRow(new string[] {
                            "0",
                            "4",
                            "Hi",
                            "1/1/0001 12:00:00 AM",
                            "00000000-1111-1111-0000-000000000001"});
                table325.AddRow(new string[] {
                            "0",
                            "5",
                            "Now",
                            "1/1/0001 12:00:00 AM",
                            "00000000-1111-1111-0000-000000000002"});
                table325.AddRow(new string[] {
                            "0",
                            "41",
                            "Brown",
                            "1/1/0001 12:00:00 AM",
                            "00000000-1111-1111-0000-000000000003"});
                table325.AddRow(new string[] {
                            "0",
                            "",
                            "It",
                            "1/1/0001 12:00:00 AM",
                            "00000000-1111-1111-0000-000000000004"});
#line 160
 await testRunner.AndAsync("the results property \'Value\' contains", ((string)(null)), table325, "And ");
#line hidden
                global::Reqnroll.Table table326 = new global::Reqnroll.Table(new string[] {
                            "ProductCategoryId",
                            "ParentProductCategoryId",
                            "Name",
                            "ModifiedDate",
                            "Rowguid"});
                table326.AddRow(new string[] {
                            "41",
                            "4",
                            "Tires and Tubes",
                            "6/1/2002 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-60e28d47dcdf"});
                table326.AddRow(new string[] {
                            "42",
                            "",
                            "Record to Delete",
                            "6/1/2005 12:00:00 AM",
                            "3c17c9ae-e906-48b4-bdd3-000000000001"});
#line 167
 await testRunner.AndAsync("the table \'SalesLT.ProductCategory\' filtered by \'ProductCategoryId > 40\' contains" +
                        "", ((string)(null)), table326, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
